### ISSUE TITLE
这个应该不是完整的项目吧？

### ISSUE THREAD

**Issue by jason-shen** [LamTech/EchoSite#1]
请问一下这个应该还差用户管理的部分吧？
我看了code好像这个不是完整的项目、有肯能我看错、请指点

谢谢

**Comment by LamTech** [comment]
用户管理随便写，你可以自定义，尝试自己接收一下参数，打印看看Sent from my Huawei phone-------- Original message --------From: Jason Shen <notifications@github.com>Date: Mon, Sep 14, 2020, 14:01To: LamTech/EchoSite <EchoSite@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [LamTech/EchoSite] 这个应该不是完整的项目吧？ (#1)

请问一下这个应该还差用户管理的部分吧？

我看了code好像这个不是完整的项目、有肯能我看错、请指点

谢谢

**Comment by jason-shen** [comment]
> 用户管理随便写，你可以自定义，尝试自己接收一下参数，打印看看S

是不是返回的时候除了发过去的数据还有加个Code：不是0 那就ok了？

谢谢

**Comment by jason-shen** [comment]
> 用户管理随便写，你可以自定义，尝试自己接收一下参数，打印看看Sent from my Huawei phone-------- Original message --------From: Jason Shen <notifications@github.com>Date: Mon, Sep 14, 2020, 14:01To: LamTech/EchoSite <EchoSite@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [LamTech/EchoSite] 这个应该不是完整的项目吧？ (#1) 请问一下这个应该还差用户管理的部分吧？ 我看了code好像这个不是完整的项目、有肯能我看错、请指点 谢谢 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

我是你的网站的用户、现在看到消息、很遗憾、这东西对我来说比较有用所以想自建一个继续用、谢谢啦

**Comment by LamTech** [comment]
请持续关注，以后我应该不会提供服务，但我会开放更好的开源版本。Sent from my Huawei phone-------- Original message --------From: Jason Shen <notifications@github.com>Date: Mon, Sep 14, 2020, 14:33To: LamTech/EchoSite <EchoSite@noreply.github.com>Cc: 非同凡想之人 <1049655193@qq.com>, Comment <comment@noreply.github.com>Subject: Re: [LamTech/EchoSite] 这个应该不是完整的项目吧？ (#1)

用户管理随便写，你可以自定义，尝试自己接收一下参数，打印看看Sent from my Huawei phone-------- Original message --------From: Jason Shen notifications@github.comDate: Mon, Sep 14, 2020, 14:01To: LamTech/EchoSite EchoSite@noreply.github.comCc: Subscribed subscribed@noreply.github.comSubject: [LamTech/EchoSite] 这个应该不是完整的项目吧？ (#1) 请问一下这个应该还差用户管理的部分吧？ 我看了code好像这个不是完整的项目、有肯能我看错、请指点 谢谢 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

我是你的网站的用户、现在看到消息、很遗憾、这东西对我来说比较有用所以想自建一个继续用、谢谢啦

**Comment by LamTech** [comment]
code为0就是正确，你也可以把请求的部分改为env或者数据库判定Sent from my Huawei phone-------- Original message --------From: Jason Shen <notifications@github.com>Date: Mon, Sep 14, 2020, 14:31To: LamTech/EchoSite <EchoSite@noreply.github.com>Cc: 非同凡想之人 <1049655193@qq.com>, Comment <comment@noreply.github.com>Subject: Re: [LamTech/EchoSite] 这个应该不是完整的项目吧？ (#1)



用户管理随便写，你可以自定义，尝试自己接收一下参数，打印看看S



是不是返回的时候除了发过去的数据还价格Code：不是0 那就ok了？

谢谢

**Comment by jason-shen** [comment]
> 请持续关注，以后我应该不会提供服务，但我会开放更好的开源版本。Sent from my Huawei phone-------- Original message --------From: Jason Shen <notifications@github.com>Date: Mon, Sep 14, 2020, 14:33To: LamTech/EchoSite <EchoSite@noreply.github.com>Cc: 非同凡想之人 <1049655193@qq.com>, Comment <comment@noreply.github.com>Subject: Re: [LamTech/EchoSite] 这个应该不是完整的项目吧？ (#1) 用户管理随便写，你可以自定义，尝试自己接收一下参数，打印看看Sent from my Huawei phone-------- Original message --------From: Jason Shen notifications@github.comDate: Mon, Sep 14, 2020, 14:01To: LamTech/EchoSite EchoSite@noreply.github.comCc: Subscribed subscribed@noreply.github.comSubject: [LamTech/EchoSite] 这个应该不是完整的项目吧？ (#1) 请问一下这个应该还差用户管理的部分吧？ 我看了code好像这个不是完整的项目、有肯能我看错、请指点 谢谢 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 我是你的网站的用户、现在看到消息、很遗憾、这东西对我来说比较有用所以想自建一个继续用、谢谢啦 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

期待这、还有， 是不是返回的时候除了发过去的数据还有加个Code：不是0 那就ok了？

谢谢
